# Generated by Django 4.1.1 on 2022-11-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_jurisprudencia_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="letrado",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="avatares"),
        ),
    ]
