# Generated by Django 4.1.1 on 2022-11-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_letrado_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="letrado",
            name="imagen",
        ),
    ]
