# Generated by Django 4.1.1 on 2022-11-04 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_letrado_imagen"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seccion",
            options={"verbose_name_plural": "Consejos"},
        ),
    ]
